# Generated by Django 3.1.12 on 2025-11-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarytransaction',
            name='merchant_id',
            field=models.CharField(db_column='merchantId', default='', max_length=64),
        ),
    ]
