# Generated by Django 3.1.12 on 2025-11-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_summarytransaction_merchant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarytransaction',
            name='total_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summarytransaction',
            name='total_amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
