# Generated by Django 3.1.12 on 2025-11-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20251121_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarytransaction',
            name='merchant_id',
            field=models.CharField(blank=True, db_column='merchantId', max_length=64, null=True),
        ),
    ]
